= Changelog

== 0.3.2

Chores

* Upgrade to Erlang 25
* Upgrade to Rebar 3.24

== 0.3.1

Bugfixes

* Handle `return_to` trace events in Brendan Gregg formatter.
* Correct types for examples in README.
* Fix Github CI workflow.

== 0.3.0

Features

* Add option to allow user to control eflambe returns to the code that calls it.
* Add SVG output format.
* Refactor code `eflambe_server` is not a named process, and one instead of it is started for each trace.
* Make `eflambe:capture/3` function synchronous

== 0.2.5

* Lock Rebar3 `project_plugins` to specific versions
* Add Rebar3 settings for code coverage and xref
* Small refactoring of code with more unit tests

== 0.2.4

Ignore garbage collection events for now.

== 0.2.3

Correct profiling of recursive function calls.

== 0.2.2

Applied some very early feedback received due to the publicity from SpawnFest. The primary fix being support for profiling functions of any arity.

== 0.2.1

First version completed during SpawnFest. I was figuring out how hex.pm worked, hence the odd first version.
